// 家族族谱数据结构
const familyData = {
    familyName: "张氏家族",
    origin: "河南省",
    establishedYear: "1850",
    description: "张氏家族历史悠久，世代相传，秉承着'厚德载物，自强不息'的家训。",

    // 家族成员数据
    members: [
        {
            id: 1,
            name: "张德厚",
            generation: 1,
            birthYear: "1850",
            deathYear: "1920",
            birthPlace: "河南省",
            occupation: "农民",
            photo: null,
            bio: "家族创始人，勤劳朴实，开垦荒地，奠定了家族基业。为人诚信，深受乡邻尊敬。",
            achievements: ["开垦荒地300亩", "修建水利设施", "资助乡邻"],
            spouse: "李氏",
            children: [2, 3]
        },
        {
            id: 2,
            name: "张文轩",
            generation: 2,
            birthYear: "1880",
            deathYear: "1960",
            birthPlace: "河南省",
            occupation: "教师",
            photo: null,
            bio: "张德厚长子，自幼聪慧，考取功名，成为当地有名的教师，教书育人40余年。",
            achievements: ["创办私塾", "培养数百名学生", "编撰族谱初稿"],
            spouse: "王氏",
            children: [4, 5, 6],
            parents: [1],
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1,
            father: 1
        },
        {
            id: 3,
            name: "张文彬",
            generation: 2,
            birthYear: "1885",
            deathYear: "1955",
            birthPlace: "河南省",
            occupation: "商人",
            photo: null,
            bio: "张德厚次子，善于经商，将家族产业扩展到多个省份，为家族积累了财富。",
            achievements: ["创立商号", "拓展家族产业", "资助公益事业"],
            spouse: "赵氏",
            children: [7, 8],
            parents: [1],
            father: 1
        },
        {
            id: 4,
            name: "张明德",
            generation: 3,
            birthYear: "1910",
            deathYear: "1995",
            birthPlace: "河南省",
            occupation: "医生",
            photo: null,
            bio: "张文轩长子，继承父亲教书育人的志向，后转学医术，成为当地名医，救死扶伤。",
            achievements: ["开设诊所", "救治无数患者", "培养医学人才"],
            spouse: "陈氏",
            children: [9, 10],
            parents: [2],
            father: 2
        },
        {
            id: 5,
            name: "张明智",
            generation: 3,
            birthYear: "1915",
            deathYear: "2000",
            birthPlace: "河南省",
            occupation: "工程师",
            photo: null,
            bio: "张文轩次子，热爱技术，参与多项国家工程建设，为基础设施建设做出贡献。",
            achievements: ["参与铁路建设", "设计桥梁工程", "技术创新"],
            spouse: "刘氏",
            children: [11],
            parents: [2],
            father: 2
        },
        {
            id: 6,
            name: "张明慧",
            generation: 3,
            birthYear: "1920",
            deathYear: "2005",
            birthPlace: "河南省",
            occupation: "教育家",
            photo: null,
            bio: "张文轩之女，女性教育的先驱者，创办女子学校，致力于提高女性教育水平。",
            achievements: ["创办女子学校", "推动女子教育", "培养女性人才"],
            spouse: "孙氏",
            children: [12, 13],
            parents: [2],
            father: 2
        },
        {
            id: 7,
            name: "张明远",
            generation: 3,
            birthYear: "1912",
            deathYear: "1998",
            birthPlace: "河南省",
            occupation: "企业家",
            photo: null,
            bio: "张文彬长子，继承家族商业事业，将家族企业发展成为当地知名企业。",
            achievements: ["扩大企业规模", "创造就业机会", "回馈社会"],
            spouse: "周氏",
            children: [14, 15],
            parents: [3],
            father: 3
        },
        {
            id: 8,
            name: "张明诚",
            generation: 3,
            birthYear: "1918",
            deathYear: "2002",
            birthPlace: "河南省",
            occupation: "艺术家",
            photo: null,
            bio: "张文彬次子，自幼喜爱艺术，成为知名画家，作品在国内外展出。",
            achievements: ["举办个人画展", "获得艺术奖项", "培养艺术人才"],
            spouse: "吴氏",
            children: [16],
            parents: [3],
            father: 3
        },
        {
            id: 9,
            name: "张建国",
            generation: 4,
            birthYear: "1940",
            deathYear: null,
            birthPlace: "河南省",
            occupation: "教授",
            photo: null,
            bio: "张明德长子，继承父亲医术，成为医科大学教授，培养医学人才。",
            achievements: ["发表学术论文", "培养医学人才", "医学研究"],
            spouse: "郑氏",
            children: [17, 18],
            parents: [4],
            father: 4
        },
        {
            id: 10,
            name: "张建华",
            generation: 4,
            birthYear: "1945",
            deathYear: null,
            birthPlace: "河南省",
            occupation: "医生",
            photo: null,
            bio: "张明德次子，继承父业，成为知名外科医生，医术精湛。",
            achievements: ["外科手术专家", "医学创新", "患者服务"],
            spouse: "冯氏",
            children: [19],
            parents: [4],
            father: 4
        },
        {
            id: 11,
            name: "张建设",
            generation: 4,
            birthYear: "1950",
            deathYear: null,
            birthPlace: "河南省",
            occupation: "建筑师",
            photo: null,
            bio: "张明智之子，继承父亲技术天赋，成为知名建筑师，设计多座标志性建筑。",
            achievements: ["设计地标建筑", "建筑创新", "城市规划"],
            spouse: "袁氏",
            children: [20, 21],
            parents: [5],
            father: 5
        },
        {
            id: 12,
            name: "张建英",
            generation: 4,
            birthYear: "1948",
            deathYear: null,
            birthPlace: "河南省",
            occupation: "教师",
            photo: null,
            bio: "张明慧长女，继承祖母教育事业，成为重点中学教师，桃李满天下。",
            achievements: ["优秀教师", "教育创新", "学生培养"],
            spouse: "马氏",
            children: [22],
            parents: [6],
            father: 6
        },
        {
            id: 13,
            name: "张建芳",
            generation: 4,
            birthYear: "1952",
            deathYear: null,
            birthPlace: "河南省",
            occupation: "作家",
            photo: null,
            bio: "张明慧次女，继承家族文化底蕴，成为知名作家，作品广受好评。",
            achievements: ["发表文学作品", "文学奖项", "文化传播"],
            spouse: "许氏",
            children: [23, 24],
            parents: [6],
            father: 6
        },
        {
            id: 14,
            name: "张建业",
            generation: 4,
            birthYear: "1945",
            deathYear: null,
            birthPlace: "河南省",
            occupation: "企业家",
            photo: null,
            bio: "张明远长子，继承家族企业，将其发展成为现代化企业集团。",
            achievements: ["企业现代化", "国际化发展", "社会责任"],
            spouse: "林氏",
            children: [25, 26],
            parents: [7],
            father: 7
        },
        {
            id: 15,
            name: "张建功",
            generation: 4,
            birthYear: "1950",
            deathYear: null,
            birthPlace: "河南省",
            occupation: "工程师",
            photo: null,
            bio: "张明远次子，热爱技术，成为高新技术企业技术总监。",
            achievements: ["技术创新", "专利发明", "技术转化"],
            spouse: "何氏",
            children: [27],
            parents: [7],
            father: 7
        },
        {
            id: 16,
            name: "张建艺",
            generation: 4,
            birthYear: "1955",
            deathYear: null,
            birthPlace: "河南省",
            occupation: "艺术家",
            photo: null,
            bio: "张明诚之子，继承父亲艺术天赋，成为知名雕塑家。",
            achievements: ["雕塑作品", "艺术展览", "文化传承"],
            spouse: "罗氏",
            children: [28],
            parents: [8],
            father: 8
        },
        {
            id: 17,
            name: "张志强",
            generation: 5,
            birthYear: "1970",
            deathYear: null,
            birthPlace: "北京市",
            occupation: "医生",
            photo: null,
            bio: "张建国长子，继承家族医学传统，成为三甲医院科室主任。",
            achievements: ["医学专家", "科研创新", "患者服务"],
            spouse: "梁氏",
            children: [],
            parents: [9],
            father: 9
        },
        {
            id: 18,
            name: "张志明",
            generation: 5,
            birthYear: "1975",
            deathYear: null,
            birthPlace: "北京市",
            occupation: "教授",
            photo: null,
            bio: "张建国次子，成为大学教授，在医学研究领域有所建树。",
            achievements: ["学术研究", "论文发表", "人才培养"],
            spouse: "宋氏",
            children: [29],
            parents: [9],
            father: 9
        },
        {
            id: 19,
            name: "张志华",
            generation: 5,
            birthYear: "1978",
            deathYear: null,
            birthPlace: "上海市",
            occupation: "医生",
            photo: null,
            bio: "张建华之子，成为知名外科医生，医术精湛。",
            achievements: ["外科专家", "手术创新", "医学研究"],
            spouse: "唐氏",
            children: [],
            parents: [10],
            father: 10
        },
        {
            id: 20,
            name: "张志远",
            generation: 5,
            birthYear: "1980",
            deathYear: null,
            birthPlace: "深圳市",
            occupation: "建筑师",
            photo: null,
            bio: "张建设长子，继承父亲建筑事业，成为知名建筑设计师。",
            achievements: ["建筑设计", "城市规划", "绿色建筑"],
            spouse: "邓氏",
            children: [30],
            parents: [11],
            father: 11
        },
        {
            id: 21,
            name: "张志文",
            generation: 5,
            birthYear: "1985",
            deathYear: null,
            birthPlace: "深圳市",
            occupation: "工程师",
            photo: null,
            bio: "张建设次子，成为结构工程师，参与多项重大工程建设。",
            achievements: ["工程技术", "项目负责", "技术创新"],
            spouse: "韩氏",
            children: [],
            parents: [11],
            father: 11
        },
        {
            id: 22,
            name: "张志婷",
            generation: 5,
            birthYear: "1980",
            deathYear: null,
            birthPlace: "广州市",
            occupation: "教师",
            photo: null,
            bio: "张建英之女，继承母亲教育事业，成为重点中学教师。",
            achievements: ["教学优秀", "教育创新", "学生指导"],
            spouse: "曹氏",
            children: [31],
            parents: [12],
            father: 12
        },
        {
            id: 23,
            name: "张志博",
            generation: 5,
            birthYear: "1982",
            deathYear: null,
            birthPlace: "杭州市",
            occupation: "作家",
            photo: null,
            bio: "张建芳长子，继承母亲文学天赋，成为知名作家。",
            achievements: ["文学作品", "文学奖项", "文化传播"],
            spouse: "彭氏",
            children: [],
            parents: [13],
            father: 13
        },
        {
            id: 24,
            name: "张志雅",
            generation: 5,
            birthYear: "1988",
            deathYear: null,
            birthPlace: "杭州市",
            occupation: "艺术家",
            photo: null,
            bio: "张建芳次女，成为知名艺术家，在艺术领域有所建树。",
            achievements: ["艺术创作", "展览举办", "文化推广"],
            spouse: "曾氏",
            children: [],
            parents: [13],
            father: 13
        },
        {
            id: 25,
            name: "张志刚",
            generation: 5,
            birthYear: "1975",
            deathYear: null,
            birthPlace: "上海市",
            occupation: "企业家",
            photo: null,
            bio: "张建业长子，继承家族企业，将其发展成为现代化企业。",
            achievements: ["企业管理", "市场拓展", "创新发展"],
            spouse: "谢氏",
            children: [32, 33],
            parents: [14],
            father: 14
        },
        {
            id: 26,
            name: "张志丽",
            generation: 5,
            birthYear: "1980",
            deathYear: null,
            birthPlace: "上海市",
            occupation: "高管",
            photo: null,
            bio: "张建业之女，成为知名企业高管，在商界有所建树。",
            achievements: ["企业管理", "战略规划", "市场开拓"],
            spouse: "邹氏",
            children: [],
            parents: [14],
            father: 14
        },
        {
            id: 27,
            name: "张志杰",
            generation: 5,
            birthYear: "1982",
            deathYear: null,
            birthPlace: "北京市",
            occupation: "工程师",
            photo: null,
            bio: "张建功之子，继承父亲技术天赋，成为技术专家。",
            achievements: ["技术研发", "专利发明", "技术创新"],
            spouse: "熊氏",
            children: [],
            parents: [15],
            father: 15
        },
        {
            id: 28,
            name: "张志艺",
            generation: 5,
            birthYear: "1985",
            deathYear: null,
            birthPlace: "成都市",
            occupation: "艺术家",
            photo: null,
            bio: "张建艺之子，继承父亲艺术天赋，成为知名艺术家。",
            achievements: ["艺术创作", "展览举办", "文化传承"],
            spouse: "金氏",
            children: [],
            parents: [16],
            father: 16
        },
        {
            id: 29,
            name: "张浩然",
            generation: 6,
            birthYear: "2005",
            deathYear: null,
            birthPlace: "北京市",
            occupation: "学生",
            photo: null,
            bio: "张志明之子，正在接受教育，品学兼优。",
            achievements: ["学习成绩优异", "特长发展", "全面发展"],
            spouse: null,
            children: [],
            parents: [18],
            father: 18
        },
        {
            id: 30,
            name: "张浩宇",
            generation: 6,
            birthYear: "2010",
            deathYear: null,
            birthPlace: "深圳市",
            occupation: "学生",
            photo: null,
            bio: "张志远之子，正在接受教育，活泼开朗。",
            achievements: ["兴趣广泛", "特长突出", "品德良好"],
            spouse: null,
            children: [],
            parents: [20],
            father: 20
        },
        {
            id: 31,
            name: "张浩月",
            generation: 6,
            birthYear: "2008",
            deathYear: null,
            birthPlace: "广州市",
            occupation: "学生",
            photo: null,
            bio: "张志婷之女，正在接受教育，聪明伶俐。",
            achievements: ["学习优秀", "才艺突出", "性格开朗"],
            spouse: null,
            children: [],
            parents: [22],
            father: 22
        },
        {
            id: 32,
            name: "张浩天",
            generation: 6,
            birthYear: "2006",
            deathYear: null,
            birthPlace: "上海市",
            occupation: "学生",
            photo: null,
            bio: "张志刚长子，正在接受教育，品学兼优。",
            achievements: ["学习成绩优异", "体育特长", "领导能力强"],
            spouse: null,
            children: [],
            parents: [25],
            father: 25
        },
        {
            id: 33,
            name: "张浩然",
            generation: 6,
            birthYear: "2010",
            deathYear: null,
            birthPlace: "上海市",
            occupation: "学生",
            photo: null,
            bio: "张志刚次子，正在接受教育，聪明好学。",
            achievements: ["思维活跃", "创新能力强", "兴趣广泛"],
            spouse: null,
            children: [],
            parents: [25],
            father: 25
        }
    ]
};

// 导出数据供其他文件使用
if (typeof module !== 'undefined' && module.exports) {
    module.exports = familyData;
}